### ISSUE TITLE
Add ability to make a 3d heatmap

### ISSUE THREAD

**Issue by kbauhaus** [mapbox/mapboxgl-powerbi#185] opened 2018-06-28 22:02 UTC
This feature was requested through communications with the Mapbox support team. Would require data driven heights.

cc @samgehret

**Comment by AlaskanPreston** [comment] 2018-06-28 22:09
Thanks Kayla!!!  Let me know if there's any way I can help answer questions.

**Comment by ryanbaumann** [comment] 2018-07-21 18:53
Duplicate of https://github.com/mapbox/mapboxgl-powerbi/issues/188 -> closing this to track in the other issue.

**Closed by ryanbaumann** 2018-07-21 18:53 UTC
