### ISSUE TITLE
Custom tileset mis-rendered in 1.1 3

### ISSUE THREAD

**Issue by cmtoomey** [mapbox/mapboxgl-powerbi#135] opened 2018-05-11 16:50 UTC
Tileset added and data appears as described. Zooming into data causes layer to drop and then re-appear.

Base on this [PR](https://github.com/mapbox/mapboxgl-powerbi/pull/132)

TilesetID: christoomey.bor5uhep

![](https://d2mxuefqeaa7sj.cloudfront.net/s_247204E7F0AB469A8BCFC237FB4151AEAA2F24CA775C4A1E96D6B83B6DEF5223_1526056614309_image.png)

![pbi2](https://user-images.githubusercontent.com/12201602/39936185-83d9c732-5500-11e8-95a7-a107bf805baa.gif)

**Comment by ryanbaumann** [comment] 2018-05-14 03:48
@cmtoomey interesting.  I'm unable to reproduce - can you share the other settings you used?  Here's my workbook file I'm using:

[seattle_hoods_powerbi-180513.zip](https://github.com/mapbox/mapboxgl-powerbi/files/1999316/seattle_hoods_powerbi-180513.zip)

**Comment by cmtoomey** [comment] 2018-05-14 17:32
Reproduced. 

Add Choropleth > Toggle Choropleth layer on and off. The layer appears to be added (has tooltips), but not rendered.

Before
![pbi_before](https://user-images.githubusercontent.com/12201602/40013329-12011728-5762-11e8-8dac-072261ca6923.gif)

After
![pbi_after](https://user-images.githubusercontent.com/12201602/40013341-1b39c5c4-5762-11e8-8711-d2ed18847011.gif)

**Comment by ryanbaumann** [comment] 2018-05-14 18:32
Great, thanks @cmtoomey - @szilardhuber @baspeti any ideas?

**Comment by ryanbaumann** [comment] 2018-05-17 03:55
This was a bug in GL JS 0.42.2.  Updating to GL JS 0.45.0 solves the problem.  This creates a much slower `Choropleth` layer experience using the data join, but that will be addressed in a near-term future version of GL JS.  Closing this issue via PR #132.

**Closed by ryanbaumann** 2018-05-17 03:55 UTC
Labels: bug
