### ISSUE TITLE
Certification of visual

### ISSUE THREAD

**Issue by whoint** [mapbox/mapboxgl-powerbi#361] opened 2019-11-28 16:10 UTC
Hi, the Mapbox visual in Power BI meets a number of use cases but uncertified visuals do not have all the functionalities.  Primarily, only native and certified visuals can be printed.  May I request for mapbox visuals in Power bI to be certified?  Prints are still widely used by our user base.  Thank you.

**Comment by otravers** [comment] 2019-12-13 23:02
Duplicate of https://github.com/mapbox/mapboxgl-powerbi/issues/202

**Closed** 2023-08-25 08:22 UTC
